### ISSUE TITLE
Actually using this library

### ISSUE THREAD

**Issue by colintsteele** [chriskr/react-date-and-time-picker#1]
You have a very nice looking component here, but because your readme is only installation instructions, I don't see how anyone can be expected to understand how to implement it.  How do you render this?  What do I import to get this to show up?  Are there properties I can give it?

If you can give me some of this information I'll be happy to update your readme for you.

**Comment by chriskr** [comment]
Hi, i thought [the example in the repo ](https://github.com/chriskr/react-date-and-time-picker/blob/master/example/src/index.js) would be enough?

{It's a very 'raw' component, all the events have to be setup separately, but in the context I'm using it it has to be like that.)

**Comment by colintsteele** [comment]
Ah I see, I was looking at the readme for the example and assumed it was for a setup.  My apologies.  

Still, I think some of that information could be easily extrapolated to the readme.  I'll try to get it up and running in my application, and if I do, I'll make a pull-request to update the readme :)

**Comment by chriskr** [comment]
Ok :)

**Comment by chriskr** [comment]
Closing this. If you have something we can reopen it.
